### PR TITLE
Fix overflow in quicktime calibration loop

### LINKED ISSUE #529: Torch events have wrong time offset on certain machines
Hey!
I've tried recording Torch events with `log_torch`, but for some machines the Torch events are wildly offset from the VizTracer events, often by a factor of 300 to 5,000 hours or so.

My hunch is the uptime of the machine may have a factor (indirectly. My primary suspect is the monotonic clock), since the below trace was obtained from a machine with ~240 days of uptime. I had another trace on a machine with ~190 days of uptime which had a less-prominent shift

VizTracer: 1.0.0
Python: 3.10.4
PyTorch: 2.5.1

image
image
image

### PR DESCRIPTION
**Pull request by Technohacker**
Fixes #529

### CODE REVIEW

File: src/viztracer/modules/quicktime.c [hunk 1]
```diff
@@ -142,12 +142,23 @@ quicktime_init()
...
         int64_t start_after = get_system_ts();
         start_ts[i] = start_before + (start_after - start_before) / 2;
-        t0_ts += start_ts[i];
-        t0_ns += start_ns[i];
     }
 
-    t0_ts /= CALIBRATE_SIZE;
-    t0_ns /= CALIBRATE_SIZE;
+    // Do the expensive average calculation outside the measurement loop
+    int64_t ts_remainder = 0, ns_remainder = 0;
```
Comment (gaogaotiantian) [inline src/viztracer/modules/quicktime.c:148]: Looks good. Could you split this into two declarations? I'm always trying to avoid declaration like this - it's often okay for a few non-pointer variables, but it gets ugly when it's a pointer or the variable name is too long or there are too many of them. Just as a habit.

Comment (Technohacker) [reply src/viztracer/modules/quicktime.c]: Sure! Pushed it now

**Comment by gaogaotiantian** [comment]
Thank you for your contribution!
